services:
  - type: web
    name: 1230-telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: ADMIN_USER_IDS
        value: ""   # e.g. "123456789,987654321"